# Generated by Django 4.2.17 on 2025-01-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='merchant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='post_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
    ]
