# Generated by Django 4.2.17 on 2025-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_receipt_image_receiptimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipts',
            field=models.ManyToManyField(to='expenses.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(null=True, upload_to='receipts/'),
        ),
        migrations.DeleteModel(
            name='ReceiptImage',
        ),
    ]
