# Generated by Django 4.2.17 on 2025-02-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expense_amount_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipts',
        ),
        migrations.AddField(
            model_name='receipt',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expense'),
        ),
    ]
